LG7n: vintf: remove android.hardware.boot from manifest
ERROR: files are incompatible:
 android.hardware.boot@1.0::IBootControl/default is deprecated; requires at least 1.2
    because it matches android.hardware.boot@1.0::IBootControl/default from /system/etc/vintf/compat
ibility_matrix.4.xml

Signed-off-by: Shirayuki39 <lorddemecrius83@proton.me>